# MODEL: text-davinci-002
# TEMPERATURE: 0.
# MAX_TOKENS: 8
# SLEEP_PER_INFER: 10

PROMPT_HEAD: "Please answer the question according to the above context.\n\n"
LINE_PREFIX: "===\n"
N_EXAMPLES: 20
K_CANDIDATES: 10
T_INFER: 5